# Generated by Django 3.0.8 on 2020-07-08 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=32)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=32)),
                ('cidade', models.CharField(max_length=32)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=32)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=14)),
                ('imagem', models.CharField(max_length=128)),
                ('horario_atendimento', models.CharField(max_length=32)),
                ('aberto', models.BooleanField()),
                ('ativo', models.BooleanField(default=True)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimento_endereco', to='core.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_taxa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('endereco_entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_endereco', to='core.Endereco')),
                ('estabelecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_estabelecimento', to='core.Estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagem', models.CharField(max_length=128)),
                ('ativo', models.BooleanField(default=True)),
                ('cardapio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_cardapio', to='core.Cardapio')),
                ('estabelecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_estabelecimento', to='core.Estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('sobrenome', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=12)),
                ('ativo', models.BooleanField(default=True)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_endereco', to='core.Endereco')),
                ('estabelecimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_estabelecimento', to='core.Estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=32)),
                ('retirar', models.BooleanField()),
                ('valor_ingrediente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtoIngrediente_ingrediente', to='core.Ingrediente')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtoIngrediente_produto', to='core.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_item', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_item', models.IntegerField()),
                ('opcao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidoItem_opcao', to='core.Opcao')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidoItem_pedido', to='core.Pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidoItem_produto', to='core.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=32)),
                ('ingrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidoIngrediente_ingrediente', to='core.Ingrediente')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidoIngrediente_pedido', to='core.Pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_usuario', to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='opcao',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opcao_produto', to='core.Produto'),
        ),
    ]
