# Generated by Django 3.0.8 on 2020-11-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_item', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_item', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='opcao',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedidoingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='pedidoingrediente',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='opcao',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='produtoingrediente',
            name='produto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='valor_pedido',
            new_name='valor_total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estabelecimento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_taxa',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cardapio',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estabelecimento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estabelecimento',
        ),
        migrations.AddField(
            model_name='pedido',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='placaVideo',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='prazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='processador',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ram',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='vista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Cardapio',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Estabelecimento',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
        migrations.DeleteModel(
            name='PedidoIngrediente',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
        migrations.DeleteModel(
            name='ProdutoIngrediente',
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_produto', to='core.Produto'),
        ),
        migrations.AddField(
            model_name='item',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_usuario', to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='item',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
