# Generated by Django 3.0.8 on 2020-11-19 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201119_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='produto',
        ),
        migrations.AddField(
            model_name='item',
            name='produto_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='produto_id', to='core.Produto'),
        ),
    ]
