# Generated by Django 3.0.8 on 2020-11-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201119_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='produto_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido', to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='item',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='item_produto', to='core.Produto'),
        ),
    ]
